### ISSUE TITLE
CKGP throws a not found exception

### ISSUE THREAD

**Issue by pedrohasselmann** [AndrewAnnex/SpiceyPy#193] opened 2017-06-16 16:00 UTC
Hi Andrew,

Scipeypy is a great library, thanks for making it available.

So, I using your spiceypy to calculate some positions and states from 67P/C-G. 
Everything runs smoothly for str2et, sce2c and spkezr until it reachs the function ckgp.
It basically returns a weird error telling me that the function is not found.

Is it this function implemented? I have version 2.0.0 and N066.
Could you help me out on this?

I thank you in advance,

Pedro H.

> CSPICE_N0066
460193921.183
2.15438313986e+13
[  3.63287867e+02  -5.67723506e+02  -2.70443184e+02  -8.90437246e-04
   2.92334359e-03   1.95441175e-03]
4.03747141222e-05
Traceback (most recent call last):
  File "spice.py", line 138, in <module>
    target_pos()
  File "spice.py", line 90, in target_pos
    spice.ckgp(int(ins), sclkst, 0e0, 'J2000')
  File "C:\Programming\Anaconda\lib\site-packages\spiceypy\spiceypy.py", line 70, in with_errcheck
    res = f(*args, **kwargs)
  File "C:\Programming\Anaconda\lib\site-packages\spiceypy\spiceypy.py", line 88, in wrapper
    raise stypes.SpiceyError("Spice returns not found for function: {}".format(f.__name__))
spiceypy.utils.support_types.SpiceyError: Spice returns not found for function: ckgp

**Comment by AndrewAnnex** [comment] 2017-06-16 17:05
oh so the function is there, but for whatever reason spice cannot get the pointing information using the time you gave it. 

If you had used CSPICE, you would not see an exception, but the last variable, the "found flag", would be false and the other values would be meaningless unless I am mistaken. Check the CSPICE docs for ckgp for more info

In spiceypy, I instead throw a python exception which is the error message in the trace you posted above. You should try surrounding the call with a python try/catch block and then decide what you want to do when you get an exception. There are a number of reasons that could cause this, looking  above a tolerance of `0e0` is probably too strict.

hope that helps

**Comment by pedrohasselmann** [comment] 2017-06-20 14:39
Hi Andrew,
Thank you for answering.
I haven't yet directly tested the CSPICE on C framework, but I have tried different 'tol' values and none worked. I start to think I'm missing loading some essential kernel or missloading it entirely.

I got 'tol=0e0' from another code written in FORTRAN77 that I'm trying to replicate.

**Comment by AndrewAnnex** [comment] 2017-06-20 15:23
Ok, let me know how it goes

**Comment by AndrewAnnex** [comment] 2017-07-03 18:11
I am closing this issue, as it is not a bug but let me know if you resolve your kernel issue

**Comment by pedrohasselmann** [comment] 2017-08-31 14:18
Hi after quite some time Andrew,

So, I keep getting the same warning, even after playing with the kernels. I have checked them carefully agaisnt the MK/ROS_V30.TM file.

I'm still wondering whether couldn't be something related to the "checkForSpiceError(f)" function. There we have the verification of the function in the libspice, right?

Pedro H.

**Comment by AndrewAnnex** [comment] 2017-08-31 14:36
well, one easy way to check is to try installing spiceypy as "editable" by using `pip -e` or by cloning the repo and using `python setup.py develop`. https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs 

At that point you can just remove the SpiceError check decorator from the function definition in the code and try running your code again.

**Comment by pedrohasselmann** [comment] 2017-09-01 13:09
I removed the @spiceFoundExceptionThrower decorator and now it recognizes the function and gives me some output.

**Comment by AndrewAnnex** [comment] 2017-09-01 14:59
can you provide some more details? Does the found flag evaluate as true or is it still false? In that case those values are just random and should not be trusted!

**Comment by pedrohasselmann** [comment] 2017-09-04 12:45
Yes, it throws me False flag.

**Comment by AndrewAnnex** [comment] 2017-09-04 13:09
can you be a bit more specific? By removing the decorator you will no longer have exceptions being thrown but that is the only change that has occurred, ie the other return values cannot be trusted as valid if the found flag evaluates to false. This invalidates the issue you are having, as it is really dependent on what kernels you are loading and what parameters you are passing in to ckgp. If you need more specific help on that, the NAIF is pretty responsive to email so you should ask them.

 I will close this issue in a few days unless this is something specifically wrong with spiceypy that can be identified.

**Comment by jdiazdelrio** [comment] 2017-09-04 13:15
Hi Pedro, Andrew --
I think it know what the problem is. CKGP in CSPICE is a mid-to-low level interface routine that looks for a data point on a CK file.  If you don't hit that data point +/- the tolerance that you introduce, the routine will send back a SPICEFALSE on the 'found' flag. See the particulars section on https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/cspice/ckgp_c.html

I haven't looked a the spiceypy implementation of the ckgp call, but I believe what it is returning is the value of the 'found' flag of the CSPICE API.  A better way to compute the pointing is as follows:
1. define the pointing direction as Z
2. Use pxform or sxform to compute the transformation matrix from 'J2000' to the frame of interests, either the spacecraft reference frame or the instrument base frame, or the instrument sensor frame.
3. Multiply Z by the matrix returned by pxform/sxform.

Hope this helps.
Jorge

**Comment by pedrohasselmann** [comment] 2017-09-04 13:26
Hi Jorge,

Thank you for your answer. Indeed, I have dropped on CKGP and moved to PXFORM. I was only attached to CKGP command because I was trying to reproduce the exact lines a collaborator has writtem in his software.

As I said before, I played a little bit with the tolerance but the results were always the same. Probably I had to really fine tune it to get a meaningful value.

Hi Andrew,

It's exactly what you described: with @spicefoundexceptionthrower decorator off I get some output (just aa array [0, 0, 0]) but they are not usable. Otherwise, the decorator passes me False.

Pedro H.

**Comment by AndrewAnnex** [comment] 2017-09-04 13:31
ok looks like this issue has been resolved, I will close it in a day or two

**Comment by AndrewAnnex** [comment] 2017-09-05 14:30
got a note from the NAIF saying that using SXFORM of PXFORM was the better thing to use instead of CKGP. closing the issue

**Closed by AndrewAnnex** 2017-09-05 14:30 UTC
Labels: not a bug, question, support

**Comment by parkerjon** [comment] 2019-01-28 23:39
Just want to note that I have had the same problem, using many combinations of c-kernels and sclk kernels, but am also opting to move on to pxform or sxform, provided they will return identical results as ckgp for identical inputs.  Can someone confirm this is the case?

For reference, I've attempted to reproduce the CSpice example in "ck required reading" below (although the exact Voyager kernels might be incorrect as I could not locate the kernels used in the example):


from spiceypy import *

sc = -32
inst = -32001
ref = 'J2000'
furnsh('kernels/sclk/vg200022.tsc')
furnsh('kernels/ck/vg2_jup_qmw_wa.bc')
furnsh('kernels/ck/vg2_jup_qmw_na.bc')
sclkdp = scencd(sc, "3/20556:17:768")
tol = sctiks(sc, "1:000")
ckgp(inst, sclkdp, tol, ref)

**Comment by AndrewAnnex** [comment] 2019-01-29 00:12
@parkerjon the NAIF communicated to me 2 years ago (see comment above) that pxform/sxform are the "better" ways to do this, but for specifics you should ask them directly.

**Comment by parkerjon** [comment] 2019-01-29 03:15
Thanks Andrew.  We will contact NAIF directly for particulars.
