### ISSUE TITLE
Cannot install spiceypy on linux centos 7.6

### ISSUE THREAD

**Issue by carmeloMagna** [AndrewAnnex/SpiceyPy#290] opened 2019-04-10 14:01 UTC
Hi I cannot find a solution to install spiceypy on CentOs system. Both using pip with `--no-cache-dir` and `python setup.py install` .

 I got: 

**error using pip**

``` pip install spiceypy --no-cache-dir
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting spiceypy
  Downloading https://files.pythonhosted.org/packages/d6/88/b0dafd30d3e0dee50388149b1667ccc26b4ba4d4152c31e50989cbaa19e1/spiceypy-2.2.0.tar.gz (177kB)
    100% |████████████████████████████████| 184kB 375kB/s 
Requirement already satisfied: numpy>=1.12.0 in /usr/lib64/python2.7/site-packages (from spiceypy) (1.16.2)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python2.7/site-packages (from spiceypy) (1.12.0)
Requirement already satisfied: certifi>=2017.1.23 in /usr/lib/python2.7/site-packages (from spiceypy) (2019.3.9)
Installing collected packages: spiceypy
  Running setup.py install for spiceypy ... error
    Complete output from command /bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-PNPDY9/spiceypy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kr2iHX/install-record.txt --single-version-externally-managed --compile:
    Wheel is Present
    running install
    ('Checking the path', '/tmp/pip-install-PNPDY9/spiceypy/cspice')
    Unable to find CSPICE at /tmp/pip-install-PNPDY9/spiceypy/cspice. Attempting to Download CSPICE For you:
    Gathering information...
    ('SYSTEM:   ', 'Linux')
    ('PROCESSOR:', 'x86_64')
    ('MACHINE:  ', '64bit')
    Downloading CSPICE for PC_Linux_GCC_64bit...
    Unpacking... (this may take some time!)
    Host OS: Linux
    /bin/sh: gcc: command not found
    Error: compilation of shared spice.so build exit status: ('32512',)
    
    ----------------------------------------
Command "/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-PNPDY9/spiceypy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kr2iHX/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-PNPDY9/spiceypy/ ```

```

** error after using the packet installer **

```
Traceback (most recent call last):
  File "whereisBCnow.py", line 14, in <module>
    import spiceypy as spice
  File "/usr/lib64/python2.7/site-packages/spiceypy/__init__.py", line 25, in <module>
    from .spiceypy import *
  File "/usr/lib64/python2.7/site-packages/spiceypy/spiceypy.py", line 28, in <module>
    from .utils.libspicehelper import libspice
  File "/usr/lib64/python2.7/site-packages/spiceypy/utils/libspicehelper.py", line 34, in <module>
    libspice = CDLL(sitePath)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib64/python2.7/site-packages/spiceypy/utils/spice.so
```
what's the problem? 
How can I exit from the empasse? 

Thank you in advance

**Comment by AndrewAnnex** [comment] 2019-04-10 15:12
you need to have the gcc compiler installed

**Comment by AndrewAnnex** [comment] 2019-04-17 17:38
I am closing this issue as it is not a bug

**Closed by AndrewAnnex** 2019-04-17 17:38 UTC
Labels: installation, not a bug

**Comment by carmeloMagna** [comment] 2019-04-18 13:44
Dear @AndrewAnnex,
thank you. Obviously it worked.

Sorry for the time wasted.

kind regards,

C
