### ISSUE TITLE
 python3.4 support

### ISSUE THREAD

**Issue by sidewalkjoe** [AndrewAnnex/SpiceyPy#181] opened 2017-02-02 14:15 UTC
Trying to pip install spiceypy, but get the following error message:

Command "python setup.py egg_info" failed with error code 1

My Python version is 3.4.4. I was running spiceypy 1.0 before, and everything worked fine. 

Thanks in advance, and please let me know if additional information is required.

**Comment by AndrewAnnex** [comment] 2017-02-02 14:54
sorry to hear that, I do need more information however like the operating system,  but I also need the full error output to further diagnose. To speculate for a moment, if you are running on windows this error might be caused by the fact that I dropped support for python 3.4, so pip can't use the provided wheels and fails during the building phase. The solution here would be to upgrade to 3.5 or 3.6 which shouldn't be difficult. If you are on linux/macOS there might be something wrong with pip based on google search, but I can think of a few other causes here as well so the full error message would help.

I will be preoccupied for the next few hours, just as a fyi, so if you find a solution on your own in that time please provide some details for others who may run into the same issue.

**Comment by sidewalkjoe** [comment] 2017-02-03 08:26
Indeed running on Win10. Sorry to hear you've dropped support for Python 3.4. No way to install it for this version at all?

**Comment by AndrewAnnex** [comment] 2017-02-04 03:32
there are a few options, for one you could install spiceypy 1.0.0 and then manually replace the python files in your site-packages to those of 1.1.0. The main issue here is that the c compiler used to compile the cspice.dll must match that of the python runtime (which differs from 2 to 3). Because of the way appveyor works, each build is run in a series so it isn't feasible to support all of the minor versions. Alternatively I may be able to rename and then upload one of the python 3 wheels as a 3.4 wheel. The last option other than updating to a newer python would be for you to setup visual studio and the related command line tools which I would not recommend.

I will investigate my swap solution soon, but that could take me more time to do than it would take you to upgrade to a newer python.

**Comment by AndrewAnnex** [comment] 2017-02-05 01:19
I found some time and uploaded prebuilt python 3.4 wheels and conda packages as per #183. 
You should now be able to pip or conda install spiceypy.

**Comment by AndrewAnnex** [comment] 2017-02-05 01:19
I will close this issue tomorrow unless there is something wrong with the artifacts.

**Closed** 2017-02-06 06:56 UTC
Labels: resolved, support
