### ISSUE TITLE
SpiceyPy No Longer Installs with Python 2.7 due to Numpy Release 1.17.0

### ISSUE THREAD

**Issue by cSchubes** [AndrewAnnex/SpiceyPy#297] opened 2019-07-30 15:49 UTC
**Bug Description**
Attempting to install SpiceyPy into a Python 2.7 environment fails with the error:
```
 RuntimeError: Python version >= 3.5 required.
```
This happens when `setup.py` attempts to install the latest release of NumPy (1.17.0), which dropped support for Python 2. 

**Expected behavior**
Installation should work inside a Python 2 environment as described in the README, or SpiceyPy should officially drop support for Python 2.

**To Reproduce**
`pip install spiceypy` inside a Python 2 environment.

**Desktop (please complete the following information):**
 - SpiceyPy Version Latest
 - OS: Ubuntu 16.04
 - OS Architecture 64 bit
 - Python Version 2.7.12
 - Python Architecture 64 bit

**Additional context**
This can be handled in one of two ways:
1. Create a final release of SpiceyPy based specifically on Numpy 1.16.4 (the last one to support Python 2) - this would require changing the `setup.py` file so the release will force installation of that specific NumPy version rather than the latest one.
2. Split SpiceyPy into a dual release structure, with one depending on the latest NumPy and the other depending on NumPy 1.16.4. This way, new SpiceyPy features will be usable on Python 2 as well.

**Comment by AndrewAnnex** [comment] 2019-08-04 08:19
For now it should be easy for users to install numpy before installing spiceypy, this is not a bug with spiceypy but a reflection that python 2.7 EOL is fast approaching. I updated the issue title to reflect this. I will look into a fix, I think this can be achieved using other means such as adding the requirement for 1.16.4 at runtime, or using requirments/setup.py functionality.

**Comment by AndrewAnnex** [comment] 2019-08-19 22:17
fixed by #298

**Closed by AndrewAnnex** 2019-08-19 22:17 UTC
Labels: not a bug
