### ISSUE TITLE
ilumin gives different values than tutorial

### ISSUE THREAD

**Issue by RossWilliamson** [AndrewAnnex/SpiceyPy#105] opened 2015-03-16 20:14 UTC
I'm currently working my way through the tutorials but running them in SpiceyPy rather than C.  Everything was working well until the remote-sensing fovint tutorial.  When I run SpiceyPy.ilumin I get significantly different values to that quoted in the remote_sensing_c.txt - i.e. for the boresight:

(C)
Vector: Cassini NAC Boresight
        Position vector of surface intercept in the IAU_PHOEBE frame (km):
           X   =           86.390
           Y   =           72.089
           Z   =            8.255
        Planetocentric coordinates of the intercept (degrees):
           LAT =            4.196
           LON =           39.844
        Phase angle (degrees):                     28.139
        Solar incidence angle (degrees):           18.247
        Emission angle (degrees):                  17.858

(SpiceyPy)
X =           86.390
Y =           72.089
Z =            8.255
LAT =            4.196
LON =           39.844
Phase Angle =           27.514 **
Solar Angle =          102.847 ** 
Emission An =           85.681 **

Call is as follows:
trgepc, surfvec, phase, solar, emissn = SpiceyPy.ilumin(
            "Ellipsoid", "PHOEBE", et, "IAU_PHOEBE", "LT+S",
            "CASSINI", bv)

**Comment by johnnycakes79** [comment] 2015-03-16 21:31
Ross, I can't immediately answer your question but I would (if you are willing) be very interested in your code for the tutorials in Python. I thought to do the same myself and prepare a stack of IPython Notebooks for teaching purposes but I've just not found the time yet...

**Comment by RossWilliamson** [comment] 2015-03-16 21:41
Sure, no problems - I need to clean them up a little and put them in notebook format.

**Comment by johnnycakes79** [comment] 2015-03-16 22:09
Great! If you were planning to put them in notebook anyway that's great but if not I can do/help with that part...

**Comment by AndrewAnnex** [comment] 2015-03-17 00:04
So thanks for posting this issue, looks like I have another thing to add to my backlog. If you could double check which kernels are loaded in the tutorial and then post them here that would be very helpful. 

Also I think that is really great that you have ipython notebooks for the tutorials, would you be willing to contribute them to the docs on this repo? I was playing around with this a few months ago, Ipython lets you export a notebook into RST format, and it should be a fairly simple process after that to integrate that with the existing sphinx docs build. If not that is ok as well, but it would be great to add links to the readme for them.

**Comment by RossWilliamson** [comment] 2015-03-17 01:25
@AndrewAnnex - Below is the meta kernel file I've been using for the fovint example

KPL/MK

This is a meta-kernel used in the lession

\begindata
KERNELS_TO_LOAD = ('../kernels/lsk/naif0008.tls',
		'../kernels/sclk/cas00084.tsc',
		'../kernels/spk/981005_PLTEPH-DE405S.bsp',
		'../kernels/spk/020514_SE_SAT105.bsp',
		'../kernels/spk/030201AP_SK_SM546_T45.bsp',
		'../kernels/fk/cas_v37.tf',
		'../kernels/ck/04135_04171pc_psiv2.bc',
                '../kernels/pck/cpck05Mar2004.tpc',
		'../kernels/ik/cas_iss_v09.ti' )

**Comment by AndrewAnnex** [comment] 2015-03-31 02:43
So I just ran through the tutorial on the Spice website and for me I got the expected values you posted that were from C (I also checked the tutorial values, they are consistent). I am not sure why you would be seeing different values, it may be system specific or you could possibly have bad kernel files. I would suggest downloading the kernels fresh from the NAIF website into an isolated location in your system and try again.

**Comment by AndrewAnnex** [comment] 2015-04-02 00:52
@RossWilliamson have you had a chance yet to double check things on your end yet? I want to close this issue as I wasn't able to reproduce it with the information provided.

**Comment by RossWilliamson** [comment] 2015-04-02 00:55
I should be able to check by the end of tomorrow - I'll get back to you

On Wed, Apr 1, 2015 at 5:52 PM, Andrew Annex <notifications@github.com>
wrote:

> @RossWilliamson <https://github.com/RossWilliamson> have you had a chance
> yet to double check things on your end yet? I want to close this issue as I
> wasn't able to reproduce it with the information provided.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AndrewAnnex/SpiceyPy/issues/105#issuecomment-88676566>
> .
>



-- 
Ross Williamson
Research Scientist - Sub-mm Group
California Institute of Technology
626-395-2647 (office)
312-504-3051 (Cell)

**Comment by AndrewAnnex** [comment] 2015-04-09 00:39
@RossWilliamson hey did you get a chance yet to look into this yet?

**Comment by AndrewAnnex** [comment] 2015-05-26 01:32
I would like to close this issue, @RossWilliamson can you confirm that you are still having this issue?

**Comment by AndrewAnnex** [comment] 2015-07-04 17:32
I am closing this issue for now, I was not able to reproduce this issue locally.

**Closed by AndrewAnnex** 2015-07-04 17:32 UTC
